### ISSUE TITLE
Doesn’t do gammons and backgammons correctly

### ISSUE THREAD

**Issue by benleviboulder** [KristianEkman/Backgammon#6]
The rules of backgammon are that if opponent hasn’t borne off any pips when I bear off all of mine, that the wager doubles (“gammon”)… and if opponent still has pips in my home board when I bear off all of mine, that’s a “backgammon.” I just played AI and gammoned it, but I didn’t receive double the wager. Please fix this error. 

Also, I’ve noticed quite a few times when the computer roles doubles in a row, e.g. double sixes, way too often for chance (1 in 36); it happens practically every game. Please confirm that your dice rolling algorithm is purely random and not weighted (i.e. cheating).

Great game, by the way, though I do question the AI, as it does moves that are not consistent with winning backgammon strategy.

**Comment by KristianEkman** [comment]
Gammons might be implemented in the future. Dice randomnrss is thorowly tested. AI is not very advanced. Most experienced humans play better and many other AIs do to. Thanks for the note.
